### ISSUE TITLE
Create a Trello Board for features and project management

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#20]
https://trello.com/

**Comment by henriiquecampos** [comment]
We already use GitHub Project features, which are very similar and more accessible too, and allows a better management of roadmaps and milestone due to integration with other GitHub features. Check it out! :smile: 

[![roadmap_image](https://i.imgur.com/K9YDj7X.png)](https://github.com/pigdevstudio/platform_template/projects/2)
