### ISSUE TITLE
Divide `wall` state into Wall Jumping and Wall Sliding states

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#32]
I don't understand Game Math very well, so I don't understand the wall state much.

But there is a jump in air bug even in the FSM revamp branch. 

https://github.com/pigdevstudio/platform_template/issues/25

To make things easier I suggest dividing `wall` state into `wall jump` and `wall slide`.

Let's discuss if this should be done and pros and cons here.

**Comment by henriiquecampos** [comment]
I don't think so.

If is better to divide the wall behavior into states, then is better to use the already available ones. E.g.:

instead of `wall_jump` just create a transition from `wall` to `jump`.

But honestly I don't think this is a must have just yet, `wall` is not that complex to need such split. :thinking:
