### ISSUE TITLE
Player stuck in wall after dashing to it

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#35]
Once I dash into the wall in the template, the character is stuck in wall state

![Player stuck in wall](https://images-ext-1.discordapp.net/external/IbRosDrpwzp6hWzEWsLWmEM-fCZAlqxYUylJpzw6p6k/https/i.imgur.com/tbpo9aT.gif)

https://imgur.com/a/W5beuJ2

IMHO this is a major bug and should be given priority.

It seems this happens when the character is touching both bottom and side walls

You should also perform a check if the `actor is_standing_on_wall` and `if true exit wall`

**Comment by Logmytech** [comment]
The issue still seems to be happening.

**Comment by Logmytech** [comment]
Now in `developement` branch, the character does wierd transistions and can't move to walk state or jump once touching wall in the direction the input is pressed.

![New Wall State bug](https://imgur.com/download/LBtUZgU)

**Comment by henriiquecampos** [comment]
This is not happening due to the transitions, is due to the slope I guess, you can test it on the left corner. 

Anyway this is a topic for another issue, the current issue is fixed with a better approach now at https://github.com/pigdevstudio/platform_template/commit/72a4217c1b9fc7c705b879960755436012a252bf

Let's move the second part to a new issue, shall we? :smile:

**Comment by henriiquecampos** [comment]
Hey, just passing by to say that yeah, there was something strange with the transitions, sorry. But I think it is fixed at  83f8c18 so I think it is good already :wink:
